const DEFAULT_ORDER_NUMBER = 10000000;
const TAX_AMOUNT = 0.05;
const CURRENCY = "USD";
const PRICE_CONVERT_USD = 100;
const DEFAULT_CONFIG_APP_ID = 1;

module.exports = {
  DEFAULT_ORDER_NUMBER,
  TAX_AMOUNT,
  CURRENCY,
  PRICE_CONVERT_USD,
  DEFAULT_CONFIG_APP_ID,
};
