/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:1961d725-2a84-4453-bf8d-95190c17c819',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_n9U98TRPx',
  aws_user_pools_web_client_id: '678i8plpeu9j97t82j5v8brlam',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  geo: {
    amazon_location_service: {
      region: 'eu-west-1',
      maps: {
        items: {
          'mapec94b6ba-saaspro': {
            style: 'VectorHereExplore',
          },
          'map6b89692a-saaspro': {
            style: 'VectorEsriStreets',
          },
        },
        default: 'map6b89692a-saaspro',
      },
      search_indices: {
        items: ['placeIndex362f56d6-saaspro', 'placeIndexaf551d40-saaspro', 'placeIndex1f250acc-saaspro'],
        default: 'placeIndex1f250acc-saaspro',
      },
    },
  },
}

export default awsmobile
