export const APIS = {
  REGISTER_BY_EMAIL: 'register-by-email',
  LOGIN_BY_EMAIL: 'login-by-email',
  MEGA_MENU: 'megamenu',
  LANDING_PAGE: 'home-page',
  PRODUCTS_IN_CATEGORY: 'products-in-category',
  RESOLVE_URL: 'resolve-url',
  CART: 'cart',
  CART_DETAILS: 'cart-detail',
  MERGE_CART: 'merge-cart',
  CHECK_CART_IS_AUTH: 'check-cart-auth',
  ADD_TO_CART: 'product-cart',
  REMOVE_PRODUCT_TO_CART: 'delete-product-cart',
  ADD_COUPON: 'add-coupon',
  REMOVE_COUPON: 'remove-coupon',
  PRODUCTS: 'products',
  SEO_PAGES: 'seo-pages',
  SEO_PRODUCT: 'seo-product',
  REVIEWS: 'reviews',
  SHIPPING_METHOD: 'shipping-method',
  PAYMENT_METHOD: 'payment-method',
}
