export const BUTTON_TYPES = {
  OUTLINE: 'outline',
  PRIMARY: 'primary',
}
export const STAR_COLOR = '#F9A000'

export const COLOR_STATUS_ORDER_CLOSED = '#AFAFAF'
export const COLOR_STATUS_ORDER_PENDING = '#F5AC1D'
export const COLOR_STATUS_ORDER_PENDING_PAYMENT = '#F5AC1D'
export const COLOR_STATUS_ORDER_CANCELED = '#FF3737'
export const COLOR_STATUS_ORDER_COMPLETE = '#82B736'
export const COLOR_STATUS_ORDER_DELIVERED = '#F95A00'
export const COLOR_STATUS_ORDER_PROCESSING = '#2F80ED'
