export const imageUrls = {
  wishlistAlreadyIn: '/assets/icon/in-wishlist.png',
  wishlistLoading: '/assets/icon/wishlist.png',
  wishlist: '/assets/icon/wishlist.png',
  iconNext: '/assets/next.svg',
  iconPrev: '/assets/icon/prev.svg',
  iconEnglish: '/assets/icon/en.png',
  iconSaudiArabian: '/assets/icon/ar.svg',
  iconVn: '/assets/icon/vn.webp',
  iconSort: '/assets/icon/sort_in.jpg',
  dropdown: '/assets/icon/dropdown.png',
  loading: '/assets/icon/loading-small.svg',
  codPayment: '/assets/icon/cod-payment.png',
  bankTBPayment: '/assets/icon/tb-payment.png',
  checkoutSelect: '/assets/icon/checkout-select.svg',
  checkoutSelectActive: '/assets/icon/checkout-select-active.svg',
}
